---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: migrate 
summary: Beim Migrieren von Speicherdaten werden Speicher-Backends manuell mithilfe von REST-APIs integriert.  Bei der Migration von VASA-Provider-Daten werden Daten aus der vorhandenen Derby-Datenbank exportiert und in die MongoDB-Datenbank importiert. 
---
= Migrieren Sie den VASA-Anbieter und aktualisieren Sie die SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== Schritte zur Migration des VASA-Anbieters

. Um Derby PORT 1527 auf den vorhandenen ONTAP tools for VMware vSphere zu aktivieren, aktivieren Sie den Root-Benutzer und melden Sie sich über SSH bei der CLI an.  Führen Sie dann den folgenden Befehl aus:
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. Stellen Sie OVA für ONTAP tools for VMware vSphere 10.4 bereit.
. Fügen Sie die vCenter Server-Instanz hinzu, die Sie zu ONTAP tools for VMware vSphere 10.4 Release migrieren möchten. Weitere Informationen finden Sie unter link:../configure/add-vcenter.html["Hinzufügen einer vCenter Server-Instanz"] für weitere Informationen.
. Integrieren Sie das Speicher-Backend lokal von den vCenter-Server-APIs für das ONTAP Tools-Plug-In.
. Führen Sie zur Migration die folgende API von Swagger oder in Postman aus.
+
curl -X POST  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs``

+
Sie können über diese URL auf Swagger zugreifen:  `\https://$FQDN_IP_PORT/', for example: `\https://10.67.25.33:8443` .

+
[]
====
*HTTP-Methode und Endpunkt*

Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

|===


| *HTTP-Methode* | *Weg* 


| POST | /api/v1 
|===
*Verarbeitungsart*

Asynchron

*Curl-Beispiel*

curl -X POST'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs'[] \ --header 'x-auth: <auth_token>' \ --header 'Content-Type: application/json' \ --data '{ "otv_ip": "xx.xx.xx.xx", "vasa_provider_credentials": { "username": "xxxxx", "password": "******" }, "database_password": "******" }'

Anforderungstext für die Migration zu anderen Releases:

{ "otv_ip": "xx.xx.xx.xx", "vasa_provider_credentials": { "Benutzername": "xxxxx", "Passwort": "*******" } }

*JSON-Ausgabebeispiel*

Es wird ein Jobobjekt zurückgegeben.  Sie sollten die Jobkennung speichern, um sie im nächsten Schritt zu verwenden.

{ "id": 123, "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35", "status": "läuft" }

====
. Verwenden Sie die folgende URI in Swagger, um den Status zu überprüfen:
+
[listing]
----
curl `\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true`
----
+
Überprüfen Sie nach Abschluss des Auftrags den Migrationsbericht.  Dieser Bericht ist in den Auftragsdaten enthalten und kann über die Auftragsantwort aufgerufen werden.

. Fügen Sie die ONTAP tools for VMware vSphere Speicheranbieter zum vCenter Server hinzu undlink:../configure/registration-process.html["Registrieren des VASA-Anbieters"] mit ONTAP tools for VMware vSphere.
. link:../manage/enable-services.html["VASA-Anbieter aktivieren"]Dienst auf ONTAP tools for VMware vSphere 10.4.
. Stoppen Sie den VASA Provider-Dienst von ONTAP tools for VMware vSphere Storage Provider 9.10/9.11/9.12/9.13 über die Wartungskonsole.
+
Löschen Sie den VASA-Anbieter nicht.

+
Nachdem der alte VASA-Provider gestoppt wurde, führt der vCenter Server ein Failover auf ONTAP tools for VMware vSphere durch. Alle Datenspeicher und VMs sind nun über ONTAP tools for VMware vSphere zugänglich und werden von diesen bedient.

. Die aus den ONTAP tools for VMware vSphere 9.xxx migrierten NFS- und VMFS-Datenspeicher sind in den ONTAP tools for VMware vSphere 10.4 erst sichtbar, nachdem der Datenspeichererkennungsjob ausgelöst wurde. Dies kann bis zu 30 Minuten dauern. Stellen Sie sicher, dass die Datenspeicher auf der Übersichtsseite der ONTAP -Tools für die Benutzeroberflächenseite des VMware vSphere-Plugins sichtbar sind.
. Führen Sie die Patchmigration mithilfe der folgenden API in Swagger oder Postman durch:
+
[]
====
*HTTP-Methode und Endpunkt*

Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

|===


| *HTTP-Methode* | *Weg* 


| PATCH | /api/v1 
|===
*Verarbeitungsart*

Asynchron

*Curl-Beispiel*

curl -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/84dr73bd-9173-65r7-w345-8ufdbb887d43`

*JSON-Ausgabebeispiel*

Es wird ein Jobobjekt zurückgegeben.  Sie sollten die Jobkennung speichern, um sie im nächsten Schritt zu verwenden.

{ "id": 123, "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35", "status": "läuft" }

Der Anforderungstext ist für den Patchvorgang leer.


NOTE: UUID ist die Migrations-UUID, die als Antwort auf die Post-Migrations-API zurückgegeben wird.

Nach dem Ausführen der Patch-Migrations-API entsprechen alle VMs der Speicherrichtlinie.

====


.Was kommt als nächstes
Nachdem Sie die Migration abgeschlossen und ONTAP Tools 10.4 beim vCenter Server registriert haben, führen Sie die folgenden Schritte aus:

* Warten Sie, bis die *Erkennung* abgeschlossen ist. Die Zertifikate werden auf allen Hosts automatisch aktualisiert.
* Warten Sie ausreichend, bevor Sie Datenspeicher- und virtuelle Maschinenvorgänge starten. Die erforderliche Wartezeit hängt von der Anzahl der Hosts, Datenspeicher und virtuellen Maschinen in der Konfiguration ab. Andernfalls kann es zu zeitweiligen Betriebsausfällen kommen.


Wenn der Konformitätsstatus der virtuellen Maschine nach dem Upgrade veraltet ist, wenden Sie die Speicherrichtlinie mit den folgenden Schritten erneut an:

. Navigieren Sie zum Datenspeicher und wählen Sie *Zusammenfassung* > *VM-Speicherrichtlinien*.
+
Der Konformitätsstatus unter *VM-Speicherrichtlinienkonformität* wird als *Veraltet* angezeigt.

. Wählen Sie die Storage VM-Richtlinie und die entsprechende VM aus
. Wählen Sie *Übernehmen*
+
Der Compliance-Status unter *VM-Speicherrichtlinien-Compliance* wird jetzt als konform angezeigt.



.Ähnliche Informationen
* link:../concepts/rbac-learn-about.html["Erfahren Sie mehr über ONTAP tools for VMware vSphere 10 RBAC"]
* link:../upgrade/upgrade-ontap-tools.html["Upgrade von ONTAP tools for VMware vSphere 10.x auf 10.4"]




== Schritte zum Aktualisieren des Speicherreplikationsadapters (SRA)

.Bevor Sie beginnen
Im Wiederherstellungsplan bezeichnet der geschützte Standort den Ort, an dem die VMs aktuell ausgeführt werden, während der Wiederherstellungsstandort der Ort ist, an dem die VMs wiederhergestellt werden. Die SRM-Oberfläche zeigt den Status des Wiederherstellungsplans mit Details zu den geschützten und den Wiederherstellungsstandorten an. Im Wiederherstellungsplan sind die Schaltflächen *CleanupP* und *Reprotect* deaktiviert, während die Schaltflächen TEST und RUN aktiviert bleiben. Dies zeigt an, dass der Standort für die Datenwiederherstellung vorbereitet ist. Stellen Sie vor der Migration des SRA sicher, dass sich ein Standort im geschützten Zustand und der andere im Wiederherstellungszustand befindet.


NOTE: Beginnen Sie nicht mit der Migration, wenn das Failover abgeschlossen ist, der erneute Schutz jedoch noch aussteht. Stellen Sie sicher, dass der erneute Schutzvorgang abgeschlossen ist, bevor Sie mit der Migration fortfahren. Wenn ein Test-Failover läuft, bereinigen Sie das Test-Failover und starten Sie die Migration.

. Führen Sie die folgenden Schritte aus, um den SRA-Adapter der ONTAP -Tools für VMware vSphere 9.xx in VMware Site Recovery zu löschen:
+
.. Gehen Sie zur Konfigurationsverwaltungsseite von VMware Live Site Recovery
.. Gehen Sie zum Abschnitt *Storage Replication Adapter*.
.. Wählen Sie im Auslassungsmenü *Konfiguration zurücksetzen*.
.. Wählen Sie im Auslassungsmenü *Löschen* aus.


. Führen Sie diese Schritte sowohl auf Schutz- als auch auf Wiederherstellungssites aus.
+
.. link:../manage/enable-services.html["Aktivieren Sie ONTAP tools for VMware vSphere -Dienste"]
.. Installieren Sie ONTAP tools for VMware vSphere 10.4 SRA-Adapter mit den Schritten inlink:../protect/configure-on-srm-appliance.html["Konfigurieren von SRA auf der VMware Live Site Recovery-Appliance"] .
.. Führen Sie auf der Benutzeroberflächenseite von VMware Live Site Recovery die Vorgänge *Arrays erkennen* und *Geräte erkennen* aus und vergewissern Sie sich, dass die Geräte wie vor der Migration angezeigt werden.



