---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: migrate 
summary: Beim Migrieren von Speicherdaten werden Speicher-Backends manuell mithilfe von REST-APIs integriert.  Bei der Migration von VASA-Provider-Daten werden Daten aus der vorhandenen Derby-Datenbank exportiert und in die MongoDB-Datenbank importiert. 
---
= Migrieren Sie den VASA-Anbieter und aktualisieren Sie die SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Befolgen Sie die Schritte in diesem Abschnitt, um den VASA Provider von ONTAP tools for VMware vSphere 9.xx auf ONTAP tools for VMware vSphere 10.4 zu migrieren und den Storage Replication Adapter (SRA) auf der VMware Live Site Recovery Appliance zu aktualisieren.



== Schritte zur Migration des VASA-Anbieters

. Um Derby PORT 1527 auf den vorhandenen ONTAP tools for VMware vSphere zu aktivieren, aktivieren Sie den Root-Benutzer und melden Sie sich über SSH bei der CLI an.  Führen Sie dann den folgenden Befehl aus:
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. Stellen Sie OVA für ONTAP tools for VMware vSphere 10.4 bereit.
. Fügen Sie die vCenter Server-Instanz hinzu, die Sie zu ONTAP tools for VMware vSphere 10.4 Release migrieren möchten. Weitere Informationen finden Sie unter link:../configure/add-vcenter.html["Hinzufügen einer vCenter Server-Instanz"] für weitere Informationen.
. Binden Sie das Speicher-Backend lokal über die vCenter Server-APIs für das ONTAP -Tools-Plug-in ein. Siehe dazulink:../configure/add-storage-backend.html["Fügen Sie ein Speicher-Backend über die vSphere-Clientschnittstelle hinzu."] für weitere Informationen.
. Sie benötigen ein Zugriffstoken, um REST-API-Anfragen zu authentifizieren. Verwenden Sie das folgende Beispiel und ersetzen Sie die Variablen durch Werte, die für Ihre Umgebung spezifisch sind.
+
+



[listing]
----
curl --request POST \
--location "https://$FQDN_IP_PORT/virtualization/api/v1/auth/login” \
--header "Content-Type: application/json" \
--header "Accept: */*" \
-d "{"username": "$MYUSER", "password": "$MYPASSWORD"}"
----
Kopieren und speichern Sie das in der Antwort zurückgegebene Zugriffstoken. . Führen Sie zur Migration die folgende API von Swagger oder in Postman aus.

+

[listing]
----
curl -X POST `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs`
----
+ Sie können Swagger über diese URL aufrufen: `\https://$FQDN_IP_PORT/`, Zum Beispiel: `\https://10.67.25.33:8443/`Die

+

[]
====
*HTTP-Methode und Endpunkt*

Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

|===


| *HTTP-Methode* | *Weg* 


| POST | /api/v1 
|===
*Verarbeitungsart*

Asynchron

*Curl-Beispiel*

[listing]
----
curl -X POST 'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs' \
--header 'x-auth: <auth_token>' \
--header 'Content-Type: application/json' \
--data '{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "******"
  },
  "database_password": "******"
}'
----
Anforderungstext für die Migration zu anderen Releases:

[listing]
----
{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "*******"
  }
}
----
*JSON-Ausgabebeispiel*

Das System gibt ein Jobobjekt zurück. Speichern Sie die Auftragskennung, um sie im nächsten Schritt zu verwenden.

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
. Verwenden Sie die folgende URI in Swagger, um den Status zu überprüfen:
+
[listing]
----
curl `\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<migration_id>?includeSubJobsAndTasks=true`
----
+
Überprüfen Sie nach Abschluss des Auftrags den Migrationsbericht in der Auftragsantwort.

. Fügen Sie die ONTAP tools for VMware vSphere -Speicheranbieter zum vCenter Server hinzu.
. Registrieren Sie den VASA-Provider mit ONTAP tools for VMware vSphere. Anweisungen finden Sie unterlink:../configure/registration-process.html["Registrieren des VASA-Anbieters"] .
. Überprüfen Sie nach der Registrierung den Namen des VASA-Anbieters und seinen Status im vSphere Client unter *Speicheranbieter*. Der VASA-Anbieter sollte online erscheinen und die erfolgreiche Registrierung bestätigen.
. link:../manage/enable-services.html["VASA-Anbieter aktivieren"]Dienst auf ONTAP tools for VMware vSphere 10.4.
. Beenden Sie die ONTAP tools for VMware vSphere Storage Provider 9.10/9.11/9.12/9.13 VASA Provider-Dienst mit den folgenden Schritten:
+
.. Öffnen Sie in ONTAP tools 9.x die Webkonsole.
.. Greifen Sie auf die Wartungskonsole zu.
.. Eingeben `1` um das Menü *Anwendungskonfiguration* auszuwählen.
.. Eingeben `5` um die VASA Provider- und SRA-Dienste zu stoppen.
.. Navigieren Sie im vSphere Client zu *Inventar* > *Speicheranbieter*.
.. Wählen Sie im Speicher-Backend den ONTAP tools 9.x VASA Provider aus und klicken Sie auf *Entfernen*.
+
Nachdem der alte VASA-Provider gestoppt wurde, führt der vCenter Server ein Failover auf ONTAP tools for VMware vSphere durch. Alle Datenspeicher und VMs sind nun über ONTAP tools for VMware vSphere zugänglich und werden von diesen bedient.



. Migrierte NFS- und VMFS-Datenspeicher werden in ONTAP tools for VMware vSphere 10.4 nach dem Datenspeichererkennungsjob angezeigt, der bis zu 30 Minuten dauern kann. Überprüfen Sie ihre Sichtbarkeit auf der Übersichtsseite.
. Führen Sie die Patchmigration mithilfe der folgenden API in Swagger oder Postman durch:
+
[]
====
*HTTP-Methode und Endpunkt*

Dieser REST-API-Aufruf verwendet die folgende Methode und den folgenden Endpunkt.

|===


| *HTTP-Methode* | *Weg* 


| PATCH | /api/v1 
|===
*Verarbeitungsart*

Asynchron

Verwenden Sie die folgende URI in Swagger:

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/<vcenter_id>/migration-jobs/<migration_id>`
----
*Curl-Beispiel*

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/d50073ce-35b4-4c51-9d2e-4ce66f802c35`
----
*JSON-Ausgabebeispiel*

Es wird ein Jobobjekt zurückgegeben.  Sie sollten die Jobkennung speichern, um sie im nächsten Schritt zu verwenden.

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
+
Der Anforderungstext ist für den Patchvorgang leer.




NOTE: UUID ist die Migrations-UUID, die als Antwort auf die Post-Migrations-API zurückgegeben wird.

Nach dem Ausführen der Patch-Migrations-API entsprechen alle VMs der Speicherrichtlinie.

.Was kommt als nächstes
Nachdem Sie die Migration abgeschlossen und ONTAP Tools 10.4 beim vCenter Server registriert haben, führen Sie die folgenden Schritte aus:

* Warten Sie, bis die *Erkennung* abgeschlossen ist. Das System aktualisiert die Zertifikate auf allen Hosts automatisch.
* Warten Sie, bevor Sie mit dem Starten von Datenspeicher- und virtuellen Maschinenvorgängen beginnen. Die Wartezeit hängt von der Anzahl der Hosts, Datenspeicher und virtuellen Maschinen ab. Wenn Sie nicht warten, kann es gelegentlich zu Fehlern kommen.


Wenn der Konformitätsstatus der virtuellen Maschine nach dem Upgrade veraltet ist, wenden Sie die Speicherrichtlinie mit den folgenden Schritten erneut an:

. Gehen Sie zum Datenspeicher und wählen Sie *Zusammenfassung* > *VM-Speicherrichtlinien*.
+
Das System zeigt den Compliance-Status unter *VM-Speicherrichtlinien-Compliance* als *Veraltet* an.

. Wählen Sie die Storage-VM-Richtlinie und die entsprechende VM aus.
. Wählen Sie *Übernehmen*.
+
Der Konformitätsstatus unter *VM-Speicherrichtlinienkonformität* wird als konform angezeigt. Verwandte Informationen

+
** link:../concepts/rbac-learn-about.html["Erfahren Sie mehr über ONTAP tools for VMware vSphere 10 RBAC"]
** link:../upgrade/upgrade-ontap-tools.html["Upgrade von ONTAP tools for VMware vSphere 10.x auf 10.4"]






== Schritte zum Aktualisieren des Speicherreplikationsadapters (SRA)

.Bevor Sie beginnen
Im Wiederherstellungsplan bezeichnet der geschützte Standort den Ort, an dem die VMs aktuell ausgeführt werden, während der Wiederherstellungsstandort der Ort ist, an dem die VMs wiederhergestellt werden. Die SRM-Oberfläche zeigt den Status des Wiederherstellungsplans mit Details zu den geschützten und den Wiederherstellungsstandorten an. Im Wiederherstellungsplan sind die Schaltflächen *CleanupP* und *Reprotect* deaktiviert, während die Schaltflächen TEST und RUN aktiviert bleiben. Dies zeigt an, dass der Standort für die Datenwiederherstellung vorbereitet ist. Stellen Sie vor der Migration des SRA sicher, dass sich ein Standort im geschützten Zustand und der andere im Wiederherstellungszustand befindet.


NOTE: Beginnen Sie nicht mit der Migration, wenn das Failover abgeschlossen ist, der erneute Schutz jedoch noch aussteht. Stellen Sie sicher, dass der erneute Schutzvorgang abgeschlossen ist, bevor Sie mit der Migration fortfahren. Wenn ein Test-Failover läuft, bereinigen Sie das Test-Failover und starten Sie die Migration.

. Führen Sie die folgenden Schritte aus, um den SRA-Adapter der ONTAP -Tools für VMware vSphere 9.xx in VMware Site Recovery zu löschen:
+
.. Gehen Sie zur Konfigurationsverwaltungsseite von VMware Live Site Recovery
.. Gehen Sie zum Abschnitt *Storage Replication Adapter*.
.. Wählen Sie im Auslassungsmenü *Konfiguration zurücksetzen*.
.. Wählen Sie im Auslassungsmenü *Löschen* aus.


. Führen Sie diese Schritte sowohl auf Schutz- als auch auf Wiederherstellungssites aus.
+
.. link:../manage/enable-services.html["Aktivieren Sie ONTAP tools for VMware vSphere -Dienste"]
.. Installieren Sie ONTAP tools for VMware vSphere 10.4 SRA-Adapter mit den Schritten inlink:../protect/configure-on-srm-appliance.html["Konfigurieren von SRA auf der VMware Live Site Recovery-Appliance"] .
.. Führen Sie auf der Benutzeroberflächenseite von VMware Live Site Recovery die Vorgänge *Arrays erkennen* und *Geräte erkennen* aus und vergewissern Sie sich, dass die Geräte wie vor der Migration angezeigt werden.



