---
permalink: deploy/prerequisites.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: Bevor Sie die ONTAP tools for VMware vSphere bereitstellen, sollten Sie mit den Speicherplatzanforderungen für das Bereitstellungspaket und einigen grundlegenden Hostsystemanforderungen vertraut sein. 
---
= ONTAP tools for VMware vSphere – Anforderungen und Konfigurationsgrenzen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie die ONTAP tools for VMware vSphere bereitstellen, sollten Sie mit den Speicherplatzanforderungen für das Bereitstellungspaket und einigen grundlegenden Hostsystemanforderungen vertraut sein.

Sie können ONTAP tools for VMware vSphere mit VMware vCenter Server Virtual Appliance (vCSA) verwenden.  Sie sollten ONTAP tools for VMware vSphere auf einem unterstützten vSphere-Client bereitstellen, der ein ESXi-System enthält.



== Systemanforderungen

* *Speicherplatzbedarf des Installationspakets pro Knoten*
+
** 15 GB für Thin Provisioning-Installationen
** 348 GB für Thick Provisioning-Installationen


* *Größenanforderungen des Hostsystems* Der empfohlene Speicher entsprechend der Bereitstellungsgröße ist in der folgenden Tabelle aufgeführt.  Um Hochverfügbarkeit (HA) bereitzustellen, benötigen Sie die dreifache Appliance-Größe, die in der Tabelle angegeben ist.


|===


| *Art der Bereitstellung* | *CPUs pro Knoten* | *Speicher (GB) pro Knoten* | *Festplattenspeicher (GB) Thick Provisioning pro Knoten* 


| Klein | 9 | 18 | 350 


| Medium | 13 | 26 | 350 


| Groß HINWEIS: Die große Bereitstellung ist nur für die HA-Konfiguration vorgesehen. | 17 | 34 | 350 
|===

NOTE: Wenn die Sicherung aktiviert ist, benötigt jeder ONTAP Tools-Cluster weitere 50 GB Speicherplatz auf dem Datenspeicher, auf dem VMs bereitgestellt werden.  Daher sind für Nicht-HA 400 GB und für HA insgesamt 1100 GB Speicherplatz erforderlich.



== Mindestanforderungen an Speicher und Anwendung

|===
| Speicher, Host und Anwendungen | Versionsanforderungen 


| ONTAP | 9.14.1, 9.15.1, 9.16.0, 9.16.1 und 9.16.1P3 FAS, ASA A-Serie, ASA C-Serie, AFF A-Serie, AFF C-Serie und ASA r2. 


| Von ONTAP -Tools unterstützte ESXi-Hosts | Ab 7.0.3 


| ONTAP -Tools unterstützten vCenter Server | Ab 7.0U3 


| VASA-Anbieter | 3,0 


| OVA-Anwendung | 10,4 


| ESXi-Host zum Bereitstellen der virtuellen Maschine mit ONTAP -Tools | 7.0U3 und 8.0U3 


| vCenter Server zum Bereitstellen der virtuellen Maschine mit ONTAP -Tools | 7.0 und 8.0 
|===

NOTE: Beginnend mit ONTAP tools for VMware vSphere 10.4 wird die Hardware der virtuellen Maschine von Version 10 auf 17 geändert.

Das Interoperability Matrix Tool (IMT) enthält die neuesten Informationen zu den unterstützten Versionen von ONTAP, vCenter Server, ESXi-Hosts und Plug-in-Anwendungen.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Interoperabilitätsmatrix-Tool"^]



== Portanforderungen

Die folgende Tabelle zeigt die von NetApp verwendeten Netzwerkports und deren Zweck. Es gibt drei verschiedene Arten von Anschlüssen:

* Externe Ports: Diese Ports sind von außerhalb des Kubernetes-Clusters oder -Knotens zugänglich.  Sie ermöglichen es Diensten, mit externen Netzwerken oder Benutzern zu kommunizieren und so die Integration mit Systemen außerhalb der Clusterumgebung zu ermöglichen.
* Inter-Node-Ports: Diese Ports ermöglichen die Kommunikation zwischen den Knoten innerhalb des Kubernetes-Clusters.  Sie werden für Clusteraufgaben wie den Datenaustausch und die Zusammenarbeit benötigt.  Bei Einzelknoten-Bereitstellungen werden die Inter-Node-Ports nur innerhalb des Knotens verwendet und benötigen keinen externen Zugriff.  Inter-Node-Ports können Datenverkehr von außerhalb des Clusters akzeptieren.  Sperren Sie den Internetzugang zwischen den Knoten mithilfe von Firewall-Regeln.
* Interne Ports: Diese Ports kommunizieren innerhalb des Kubernetes-Clusters über ClusterIP-Adressen.  Sie sind nicht extern zugänglich und müssen nicht zu Firewall-Regeln hinzugefügt werden.



NOTE: Stellen Sie sicher, dass sich alle ONTAP Tool-Knoten im selben Subnetz befinden, um eine unterbrechungsfreie Kommunikation untereinander aufrechtzuerhalten.


|===
| *Dienst-/Komponentenname* | *Hafen* | *Protokoll* | *Anschlusstyp* | *Beschreibung* 


| ntv-gateway-svc (LB) | 443, 8443 | TCP | Extern | Durchgangsport für eingehende Kommunikation für den VASA-Provider-Dienst. Auf diesem Port werden das selbstsignierte Zertifikat des VASA-Anbieters und das benutzerdefinierte CA-Zertifikat gehostet. 


| SSH | 22 | TCP | Extern | Secure Shell für die Anmeldung am Remote-Server und die Ausführung von Befehlen. 


| rke2-Server | 9345 | TCP | Zwischenknoten | RKE2 Supervisor API (Beschränkung auf vertrauenswürdige Netzwerke). 


| kube-apiserver | 6443 | TCP | Zwischenknoten | Kubernetes API-Server-Port (auf vertrauenswürdige Netzwerke beschränken). 


| rpcbind/portmapper | 111 | TCP/UDP | Zwischenknoten | Wird für die RPC-Kommunikation zwischen Diensten verwendet. 


| coredns (DNS) | 53 | TCP/UDP | Zwischenknoten | Domain Name System (DNS)-Dienst zur Namensauflösung innerhalb des Clusters. 


| NTP | 123 | UDP | Zwischenknoten | Netzwerkzeitprotokoll (NTP) zur Zeitsynchronisation. 


| etcd | 2379, 2380, 2381 | TCP | Zwischenknoten | Schlüsselwertspeicher für Clusterdaten. 


| kube-vip | 2112 | TCP | Zwischenknoten | Kubernetes API-Server-Port. 


| kubelet | 10248, 10250 | TCP | Zwischenknoten | Kubernetes-Komponente 


| kube-controller | 10257 | TCP | Zwischenknoten | Kubernetes-Komponente 


| Cloud-Controller | 10258 | TCP | Zwischenknoten | Kubernetes-Komponente 


| kube-scheduler | 10259 | TCP | Zwischenknoten | Kubernetes-Komponente 


| kube-proxy | 10249, 10256 | TCP | Zwischenknoten | Kubernetes-Komponente 


| Kaliko-Knoten | 9091, 9099 | TCP | Zwischenknoten | Calico-Netzwerkkomponente. 


| containerd | 10010 | TCP | Zwischenknoten | Container-Daemon-Dienst. 


| VXLAN (Flannel) | 8472 | UDP | Zwischenknoten | Overlay-Netzwerk für die Pod-Kommunikation. 
|===

NOTE: Bei HA-Bereitstellungen muss sichergestellt werden, dass der UDP-Port 8472 zwischen allen Knoten geöffnet ist.  Dieser Port ermöglicht die Kommunikation zwischen Pods über verschiedene Knoten hinweg; durch Blockierung wird die Netzwerkverbindung zwischen den Knoten unterbrochen.



== Konfigurationslimits für die Bereitstellung von ONTAP tools for VMware vSphere

Sie können die folgende Tabelle als Leitfaden zum Konfigurieren von ONTAP tools for VMware vSphere verwenden.

|===


| *Einsatz* | *Typ* | *Anzahl der vVols* | *Anzahl der Hosts* 


| Nicht-HA | Klein (S) | ~12K | 32 


| Nicht-HA | Mittel (M) | ~24K | 64 


| Hohe Verfügbarkeit | Klein (S) | ~24K | 64 


| Hohe Verfügbarkeit | Mittel (M) | ~50k | 128 


| Hohe Verfügbarkeit | Groß (L) | ~100k | 256 [HINWEIS] Die Anzahl der Hosts in der Tabelle zeigt die Gesamtzahl der Hosts aus mehreren vCentern. 
|===


== ONTAP tools for VMware vSphere – Storage Replication Adapter (SRA)

Die folgende Tabelle zeigt die pro VMware Live Site Recovery-Instanz unterstützten Zahlen mit ONTAP tools for VMware vSphere.

|===
| *vCenter-Bereitstellungsgröße* | *Klein* | *Medium* 


| Gesamtzahl der virtuellen Maschinen, die für den Schutz mithilfe arraybasierter Replikation konfiguriert sind | 2000 | 5000 


| Gesamtzahl der Array-basierten Replikationsschutzgruppen | 250 | 250 


| Gesamtzahl der Schutzgruppen pro Wiederherstellungsplan | 50 | 50 


| Anzahl replizierter Datenspeicher | 255 | 255 


| Anzahl der VMs | 4000 | 7000 
|===
Die folgende Tabelle zeigt die Anzahl von VMware Live Site Recovery und die entsprechenden ONTAP tools for VMware vSphere .

|===


| *Anzahl der VMware Live Site Recovery-Instanzen* | * Größe der ONTAP -Toolbereitstellung* 


| Bis zu 4 | Klein 


| 4 bis 8 | Medium 


| Mehr als 8 | Groß 
|===
Weitere Informationen finden Sie unter  https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/overview/site-recovery-manager-system-requirements/operational-limits-of-site-recovery-manager.html["Betriebsgrenzen von VMware Live Site Recovery"] .
