---
permalink: protect/map-folder.html 
sidebar: sidebar 
keywords:  
summary: Sie sollten Ihre Ordner auf der geschützten Site und der Wiederherstellungssite zuordnen, um die Kommunikation zwischen ihnen zu ermöglichen. 
---
= Konfigurieren von Ordnerzuordnungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten Ihre Ordner auf der geschützten Site und der Wiederherstellungssite zuordnen, um die Kommunikation zwischen ihnen zu ermöglichen.

.Bevor Sie beginnen
Sie sollten die geschützten und Wiederherstellungssites verbunden haben.

.Schritte
. Melden Sie sich bei vCenter Server an und wählen Sie *Site Recovery* > *Sites*.
. Wählen Sie Ihre geschützte Site aus und wählen Sie *Verwalten*.
. Wählen Sie auf der Registerkarte „Verwalten“ das Symbol „*Ordnerzuordnungen* > *Ordner*“, um eine neue Ordnerzuordnung zu erstellen.
. Führen Sie im Assistenten „Ordnerzuordnung erstellen“ die folgenden Schritte aus:
+
.. Wählen Sie *Zuordnungen für Ordner mit übereinstimmenden Namen automatisch vorbereiten* und wählen Sie *Weiter*.
.. Wählen Sie die erforderlichen Rechenzentrumsobjekte für die geschützten und Wiederherstellungsstandorte aus und wählen Sie *Zuordnungen hinzufügen*.
.. Wählen Sie *Weiter*, nachdem die Zuordnungen erfolgreich erstellt wurden.
.. Wählen Sie das zuvor zum Erstellen der Rückwärtszuordnung verwendete Objekt aus und wählen Sie dann *Fertig*.




.Ergebnis
Auf der Seite „Ordnerzuordnungen“ werden die Ressourcen der geschützten Site und der Wiederherstellungssite angezeigt.  Sie können dieselben Schritte für andere Netzwerke in Ihrer Umgebung ausführen.
