---
permalink: protect/update-credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: Damit VMware Live Site Recovery mit SRA kommunizieren kann, sollten Sie die SRA-Anmeldeinformationen auf dem VMware Live Site Recovery-Server aktualisieren, wenn Sie die Anmeldeinformationen geändert haben. 
---
= SRA-Anmeldeinformationen aktualisieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Damit VMware Live Site Recovery mit SRA kommunizieren kann, sollten Sie die SRA-Anmeldeinformationen auf dem VMware Live Site Recovery-Server aktualisieren, wenn Sie die Anmeldeinformationen geändert haben.

.Bevor Sie beginnen
Sie sollten die im Thema genannten Schritte ausgeführt habenlink:../protect/configure-on-srm-appliance.html["Konfigurieren von SRA auf der VMware Live Site Recovery-Appliance"] .

.Schritte
. Führen Sie die folgenden Befehle aus, um den im Ordner „VMware Live Site Recovery“ zwischengespeicherten Benutzernamen und das Kennwort für die ONTAP -Tools zu löschen:
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd conf/`
.. `rm -rf *`


. Führen Sie den Perl-Befehl aus, um SRA mit den neuen Anmeldeinformationen zu konfigurieren:
+
.. `cd ..`
.. `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <OTV_ADMIN_USERNAME> --otv-password <OTV_ADMIN_PASSWORD> --vcenter-guid <VCENTER_GUID>`Der Kennwortwert muss in einfache Anführungszeichen gesetzt werden.
+
Es wird eine Erfolgsmeldung angezeigt, die bestätigt, dass die Speicheranmeldeinformationen gespeichert wurden.  SRA kann über die bereitgestellte IP-Adresse, den Port und die Anmeldeinformationen mit dem SRA-Server kommunizieren.




