---
permalink: concepts/ontap-tools-overview.html 
sidebar: sidebar 
keywords:  
summary: ONTAP tools for VMware vSphere sind eine Sammlung von Tools für das Lebenszyklusmanagement virtueller Maschinen.  Es lässt sich in das VMware-Ökosystem integrieren und hilft bei der Bereitstellung, dem grundlegenden Schutz und der Notfallwiederherstellung virtueller Maschinen. 
---
= ONTAP tools for VMware vSphere – Übersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere sind ein Satz von Tools für das Lebenszyklusmanagement virtueller Maschinen. Es lässt sich in das VMware-Ökosystem integrieren, um bei der Bereitstellung von Datenspeichern zu helfen und einen grundlegenden Schutz für virtuelle Maschinen bereitzustellen.  ONTAP tools for VMware vSphere sind eine Sammlung horizontal skalierbarer, ereignisgesteuerter Microservices, die als Open Virtual Appliance (OVA) bereitgestellt werden.  Diese Version integriert REST API mit ONTAP.

ONTAP tools for VMware vSphere bestehen aus Folgendem:

* Funktionen virtueller Maschinen wie Basisschutz und Notfallwiederherstellung
* VASA-Anbieter für granulares VM-Management
* Speicherrichtlinienbasierte Verwaltung
* Speicherreplikationsadapter (SRA)

