---
sidebar: sidebar 
permalink: automation/first-call.html 
keywords: ontap tools for vmware vsphere rest api reference, first rest api call, acquire access token 
summary: Sie können einen API-Aufruf mit curl ausgeben, um mit den ONTAP tools for VMware vSphere 10 REST-API zu beginnen. 
---
= Ihre ersten ONTAP tools for VMware vSphere 10 REST-API-Aufruf
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können einen API-Aufruf mit curl ausgeben, um mit den ONTAP tools for VMware vSphere 10 REST-API zu beginnen.



== Bevor Sie beginnen

Sie sollten die erforderlichen Informationen und Parameter in den Curl-Beispielen überprüfen.

.Erforderliche Informationen
Sie benötigen Folgendes:

* ONTAP tools for VMware vSphere 10 IP-Adresse oder FQDN sowie den Port
* Anmeldeinformationen für den ONTAP Tools Manager-Administrator (Benutzername und Passwort)


.Parameter und Variablen
Die unten dargestellten Curl-Beispiele enthalten Variablen im Bash-Stil.  Sie können diese Variablen in der Bash-Umgebung festlegen oder sie vor der Ausführung der Befehle manuell aktualisieren.  Wenn Sie die Variablen festlegen, ersetzt die Shell die Werte in jedem Befehl, bevor dieser ausgeführt wird.  Die Variablen werden in der folgenden Tabelle beschrieben.

[cols="25,75"]
|===
| Variable | Beschreibung 


| $FQDN_IP_PORT | Der vollqualifizierte Domänenname oder die IP-Adresse des ONTAP Tools Manager zusammen mit der Portnummer. 


| $MEINBENUTZER | Benutzername für das ONTAP Tools Manager-Konto. 


| $MEINPASSWORT | Mit dem Benutzernamen des ONTAP Tools Manager verknüpftes Kennwort. 


| $ACCESS_TOKEN | Das vom ONTAP Tools Manager ausgestellte Zugriffstoken. 
|===
Die folgenden Befehle und Ausgaben der Linux-CLI veranschaulichen, wie eine Variable gesetzt und angezeigt werden kann:

[listing]
----
FQDN_IP_PORT=172.14.31.224:8443
echo $FQDN_IP
172.14.31.224:8443
----


== Schritt 1: Abrufen eines Zugriffstokens

Sie müssen ein Zugriffstoken erwerben, um die REST-API zu verwenden.  Nachfolgend wird ein Beispiel für die Anforderung eines Zugriffstokens dargestellt.  Sie sollten die entsprechenden Werte für Ihre Umgebung einsetzen.

[source, curl]
----
curl --request POST \
--location "https://$FQDN_IP_PORT/virtualization/api/v1/auth/login” \
--header "Content-Type: application/json" \
--header "Accept: */*" \
-d "{"username": "$MYUSER", "password": "$MYPASSWORD"}"
----
Kopieren und speichern Sie das in der Antwort bereitgestellte Zugriffstoken.



== Schritt 2: Ausführen des REST-API-Aufrufs

Nachdem Sie über ein Zugriffstoken verfügen, können Sie mit curl einen REST-API-Aufruf tätigen.  Fügen Sie das im ersten Schritt erworbene Zugriffstoken ein.

.Curl-Beispiel
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP_PORT/virtualization/api/v1/vcenters" \
--header "Accept: */*" \
--header "x-auth: $ACCESS_TOKEN"
----
Die JSON-Antwort enthält eine Liste der für den ONTAP Tools Manager konfigurierten VMware vCenter-Instanzen.
