---
permalink: manage/reports.html 
sidebar: sidebar 
keywords:  
summary: ONTAP tools for VMware vSphere Plug-in bieten Berichte für virtuelle Maschinen und Datenspeicher. 
---
= ONTAP -Tools-Berichte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere Plug-in bieten Berichte für virtuelle Maschinen und Datenspeicher.  Wenn Sie im Abschnitt „Verknüpfungen“ des vCenter-Clients das Plug-In-Symbol „NetApp ONTAP tools for VMware vSphere“ auswählen, navigiert die Benutzeroberfläche zur Seite „Übersicht“.  Wählen Sie die Registerkarte „Berichte“ aus, um den Bericht zur virtuellen Maschine und den Datenspeichern anzuzeigen.

Der Bericht „Virtuelle Maschinen“ zeigt die Liste der erkannten virtuellen Maschinen (sollte mindestens eine Festplatte aus ONTAP Speicher-basierten Datenspeichern haben) mit Leistungsmetriken.  Wenn Sie den VM-Datensatz erweitern, werden alle datenträgerbezogenen Datenspeicherinformationen angezeigt.

Der Datastores-Bericht zeigt die Liste der erkannten oder erkannten ONTAP tools for VMware vSphere verwaltete Datastores, die vom ONTAP -Speicher-Backend aller Typen mit Leistungsmetriken bereitgestellt werden.

Mit der Option „Spalten verwalten“ können Sie verschiedene Spalten ausblenden oder anzeigen.
