---
permalink: manage/reset-manager-password.html 
sidebar: sidebar 
keywords:  
summary: Wenn Sie das Kennwort für den ONTAP Tools Manager vergessen haben, können Sie die Administratoranmeldeinformationen mithilfe des von den ONTAP tools for VMware vSphere Wartungskonsole generierten Tokens zurücksetzen. 
---
= Kennwort für den ONTAP Tools Manager zurücksetzen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie das Kennwort für den ONTAP Tools Manager vergessen haben, können Sie die Administratoranmeldeinformationen mithilfe des von den ONTAP tools for VMware vSphere Wartungskonsole generierten Tokens zurücksetzen.

.Schritte
. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Wählen Sie auf dem Anmeldebildschirm die Option *Passwort zurücksetzen*.
+
Um das Managerkennwort zurückzusetzen, müssen Sie das Reset-Token mithilfe der ONTAP tools for VMware vSphere Wartungskonsole generieren.

+
.. Öffnen Sie vom vCenter Server aus die Wartungskonsole
.. Geben Sie „2“ ein, um die Option „Systemkonfiguration“ auszuwählen
.. Geben Sie „3“ ein, um das Benutzerkennwort „maint“ zu ändern.


. Geben Sie im Popup-Fenster zum Ändern des Kennworts das Token zum Zurücksetzen des Kennworts, den Benutzernamen und die neuen Kennwortdetails ein.
. Wählen Sie *Zurücksetzen*, um die Änderungen zu übernehmen.  Nach erfolgreicher Kennwortzurücksetzung können Sie sich mit dem neuen Kennwort anmelden.

