---
permalink: manage/update-vcenter-credentials.html 
sidebar: sidebar 
keywords:  
summary: Sie können die Anmeldeinformationen für vCenter Server und ONTAP mithilfe der Wartungskonsole aktualisieren. 
---
= Aktualisieren Sie die vCenter Server- und ONTAP -Anmeldeinformationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die vCenter Server-Instanz und die ONTAP Anmeldeinformationen mithilfe der Wartungskonsole aktualisieren.

.Bevor Sie beginnen
Sie benötigen die Anmeldedaten eines Wartungsbenutzers.

*Über diese Aufgabe*

Wenn Sie die Anmeldeinformationen für vCenter Server, ONTAP oder Data LIF nach der Bereitstellung geändert haben, müssen Sie die Anmeldeinformationen mit diesem Verfahren aktualisieren.

.Schritte
. Öffnen Sie vom vCenter Server aus eine Konsole für den VASA-Anbieter.
. Melden Sie sich als Wartungsbenutzer an.
. Eingeben `2` , um das Systemkonfigurationsmenü auszuwählen.
. Eingeben `9` um die ONTAP Anmeldeinformationen zu ändern.
. Eingeben `10` um die vCenter-Anmeldeinformationen zu ändern.

